### ISSUE TITLE
如何省略扩展名加载vue文件

### ISSUE THREAD

**Issue by yujiaao** [lceric/vite-vue2-demo#1]
这个项目里用的是
```
import App from './App.vue';
```
加载正常，如何用配置成用省略的写法呢？
如：
```
import App from './App';
```
想把旧的项目改用vite开发，都要改的话，改的地方太多了

**Comment by lceric** [comment]
不太建议配置自定义的类型，比如`.vue`，不过你可以试着配置一下`resolve.extensions`
```js
{
  plugins: [],
  css: {},
  resolve: {
    alias: [],
    // .vue
    extensions: ['.vue', '.mjs', '.js', '.ts', '.jsx', '.tsx', '.json'],
  },
}
```


见文档[https://vitejs.dev/config/#resolve-extensions](https://vitejs.dev/config/#resolve-extensions)

# resolve.extensions
**Type**: `string[]`
**Default:**: `['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json']`
List of file extensions to try for imports that omit extensions. Note it is **NOT** recommended to omit extensions for custom import types (e.g. `.vue`) since it can interfere with IDE and type support.
